package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"time"

	"github.com/example/ds-technical-assessment/graph/model"
	"github.com/example/ds-technical-assessment/internal/auth"
)

// UpdateElement is the resolver for the updateElement field.
func (r *mutationResolver) UpdateElement(ctx context.Context, uri string, title string) (*model.Element, error) {
	panic(fmt.Errorf("not implemented: UpdateElement - updateElement"))
}

// Elements is the resolver for the elements field.
func (r *queryResolver) Elements(ctx context.Context, first *int32, after *string, filter *model.FieldValueFilter) (*model.ElementConnection, error) {
	userID, err := auth.GetUserID(ctx)
	if err != nil {
		return nil, err
	}

	limit := int32(20)
	if first != nil {
		limit = *first
	}
	if limit > 100 {
		limit = 100
	}
	if limit < 1 {
		limit = 1
	}

	afterURI := ""
	if after != nil && *after != "" {
		afterURI, err = decodeCursor(*after)
		if err != nil {
			return nil, err
		}
	}

	args := []any{userID} // $1 = userID

	query := `
		SELECT
			e.uri,
			e.title,
			e.type_uri,
			e.space_uri,
			e.creation_date,
			u.display_name AS author
		FROM elements e
		JOIN users u ON e.author = u.uri
		WHERE e.space_uri IN (
			SELECT space_uri FROM user_spaces WHERE user_uri = $1
		)
	`
	if filter != nil {
		args = append(args, filter.FieldURI, filter.Value)
		fieldParam := len(args) - 1
		valParam := len(args)
		query += fmt.Sprintf(`
			AND e.uri IN (
				SELECT element_uri
				FROM element_field_values
				WHERE field_uri = $%d
				  AND COALESCE(
				        value_text,
				        CAST(value_number AS TEXT),
				        CAST(value_boolean AS TEXT),
				        CAST(value_date AS TEXT)
				      ) = $%d
			)
		`, fieldParam, valParam)
	}

	if afterURI != "" {
		args = append(args, afterURI)
		query += fmt.Sprintf(` AND e.uri > $%d`, len(args))
	}

	args = append(args, limit+1)
	query += fmt.Sprintf(` ORDER BY e.uri ASC LIMIT $%d`, len(args))
	rows, err := r.database.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("querying elements: %w", err)
	}
	defer func() {
		if closeErr := rows.Close(); closeErr != nil && err == nil {
			err = closeErr
		}
	}()

	elements := make([]*model.Element,0, limit + 1)
	for rows.Next() {
		elem := &model.Element{}
		var creationDateMs int64
		err := rows.Scan(
			&elem.URI,
			&elem.Title,
			&elem.TypeURI,
			&elem.SpaceURI,
			&creationDateMs,
			&elem.Author,
		)
		if err != nil {
			return nil, fmt.Errorf("scanning element: %w", err)
		}
		elem.CreationDate = time.UnixMilli(creationDateMs).UTC().Format(time.RFC3339)
		elements = append(elements, elem)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("reading element rows: %w", err)
	}

	hasNextPage := false
	if int32(len(elements)) > limit {
		hasNextPage = true
		elements = elements[:limit]
	}

	if len(elements) > 0 {
		if err := loadFieldValues(ctx, r.database, elements); err != nil {
			return nil, err
		}
	}

	edges := make([]*model.ElementEdge, len(elements))
	for i, elem := range elements {
		edges[i] = &model.ElementEdge{
			Cursor: encodeCursor(elem.URI),
			Node:   elem,
		}
	}
	var endCursor *string
	if len(elements) > 0 {
		c := encodeCursor(elements[len(elements)-1].URI)
		endCursor = &c
	}

	return &model.ElementConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNextPage,
			EndCursor:   endCursor,
		},
	}, nil
}



// ElementUpdated is the resolver for the elementUpdated field.
func (r *subscriptionResolver) ElementUpdated(ctx context.Context) (<-chan *model.Element, error) {
	panic(fmt.Errorf("not implemented: ElementUpdated - elementUpdated"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
