package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"database/sql"
	"encoding/base64"
	"fmt"
	"strings"
	"time"

	"github.com/example/ds-technical-assessment/graph/model"
	"github.com/example/ds-technical-assessment/internal/auth"
)

func getUserID(ctx context.Context) (string, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok || userID == "" {
		return "", fmt.Errorf("unauthorized: missing user ID")
	}
	return userID, nil
}

func encodeCursor(uri string) string {
	return base64.StdEncoding.EncodeToString([]byte(uri))
}


func decodeCursor(cursor string) (string, error) {
	b, err := base64.StdEncoding.DecodeString(cursor)
	if err != nil {
		// %w is a special verb in fmt.Errorf that WRAPS the original error.
		// This preserves the original error so callers can inspect it with
		// errors.Is() or errors.As() if needed.
		return "", fmt.Errorf("invalid cursor: %w", err)
	}
	return string(b), nil
}


// UpdateElement is the resolver for the updateElement field.
func (r *mutationResolver) UpdateElement(ctx context.Context, uri string, title string) (*model.Element, error) {
	panic(fmt.Errorf("not implemented: UpdateElement - updateElement"))
}

// Elements is the resolver for the elements field.
func (r *queryResolver) Elements(ctx context.Context, first *int32, after *string, filter *model.FieldValueFilter) (*model.ElementConnection, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	limit := int32(20)
	if first != nil {
		limit = *first
	}
	if limit > 100 {
		limit = 100
	}
	if limit < 1 {
		limit = 1
	}

	afterURI := ""
	if after != nil && *after != "" {
		afterURI, err = decodeCursor(*after)
		if err != nil {
			return nil, err
		}
	}

	args := []any{userID} // $1 = userID

	query := `
		SELECT
			e.uri,
			e.title,
			e.type_uri,
			e.space_uri,
			e.creation_date,
			u.display_name AS author
		FROM elements e
		JOIN users u ON e.author = u.uri
		WHERE e.space_uri IN (
			SELECT space_uri FROM user_spaces WHERE user_uri = $1
		)
	`
	if filter != nil {
		args = append(args, filter.FieldURI, filter.Value)
		fieldParam := len(args) - 1
		valParam := len(args)
		query += fmt.Sprintf(`
			AND e.uri IN (
				SELECT element_uri
				FROM element_field_values
				WHERE field_uri = $%d
				  AND COALESCE(
				        value_text,
				        CAST(value_number AS TEXT),
				        CAST(value_boolean AS TEXT),
				        CAST(value_date AS TEXT)
				      ) = $%d
			)
		`, fieldParam, valParam)
	}

	if afterURI != "" {
		args = append(args, afterURI)
		query += fmt.Sprintf(` AND e.uri > $%d`, len(args))
	}

	args = append(args, limit+1)
	query += fmt.Sprintf(` ORDER BY e.uri ASC LIMIT $%d`, len(args))
	rows, err := r.database.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("querying elements: %w", err)
	}
	defer rows.Close()

	var elements []*model.Element
	for rows.Next() {
		elem := &model.Element{}
		var creationDateMs int64
		err := rows.Scan(
			&elem.URI,
			&elem.Title,
			&elem.TypeURI,
			&elem.SpaceURI,
			&creationDateMs,
			&elem.Author,
		)
		if err != nil {
			return nil, fmt.Errorf("scanning element: %w", err)
		}
		elem.CreationDate = time.UnixMilli(creationDateMs).UTC().Format(time.RFC3339)
		elements = append(elements, elem)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("reading element rows: %w", err)
	}

	hasNextPage := false
	if int32(len(elements)) > limit {
		hasNextPage = true
		elements = elements[:limit]
	}

	if len(elements) > 0 {
		if err := loadFieldValues(ctx, r.database, elements); err != nil {
			return nil, err
		}
	}

	edges := make([]*model.ElementEdge, len(elements))
	for i, elem := range elements {
		edges[i] = &model.ElementEdge{
			Cursor: encodeCursor(elem.URI),
			Node:   elem,
		}
	}
	var endCursor *string
	if len(elements) > 0 {
		c := encodeCursor(elements[len(elements)-1].URI)
		endCursor = &c
	}

	return &model.ElementConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNextPage,
			EndCursor:   endCursor,
		},
	}, nil
}

func loadFieldValues(ctx context.Context, db *sql.DB, elements []*model.Element) error {
	elemByURI := make(map[string]*model.Element, len(elements))
	for _, e := range elements {
		elemByURI[e.URI] = e
	}
	uris := make([]any, len(elements))
	for i, e := range elements {
		uris[i] = e.URI
	}
	placeholderSlice := make([]string, len(uris))
	for i := range placeholderSlice {
		placeholderSlice[i] = fmt.Sprintf("$%d", i+1)
	}
	placeholder := strings.Join(placeholderSlice, ",")
	query := fmt.Sprintf(`
		SELECT
			efv.uri,
			efv.element_uri,
			efv.value_text,
			efv.value_number,
			efv.value_date,
			efv.value_boolean,
			efv.value_json,
			f.uri  AS field_uri,
			f.name AS field_name,
			f.field_type
		FROM element_field_values efv
		JOIN fields f ON efv.field_uri = f.uri
		WHERE efv.element_uri IN (%s)
		ORDER BY efv.element_uri, f.name
	`, placeholder)

	rows, err := db.QueryContext(ctx, query, uris...)
	if err != nil {
		return fmt.Errorf("querying field values: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var (
			fvURI      string
			elemURI    string
			valueText  sql.NullString
			valueNum   sql.NullFloat64
			valueDate  sql.NullInt64
			valueBool  sql.NullBool
			valueJSON  sql.NullString
			fieldURI   string
			fieldName  string
			fieldType  string
		)

		err := rows.Scan(
			&fvURI,
			&elemURI,
			&valueText,
			&valueNum,
			&valueDate,
			&valueBool,
			&valueJSON,
			&fieldURI,
			&fieldName,
			&fieldType,
		)
		if err != nil {
			return fmt.Errorf("scanning field value: %w", err)
		}
		var value any
		switch {
		case valueText.Valid:
			value = valueText.String
		case valueNum.Valid:
			value = valueNum.Float64
		case valueBool.Valid:
			value = valueBool.Bool
		case valueDate.Valid:
			value = time.UnixMilli(valueDate.Int64).UTC().Format(time.RFC3339)
		case valueJSON.Valid:
			value = valueJSON.String
		}

		fv := &model.FieldValue{
			URI:   fvURI,
			Value: value,
			Field: &model.Field{
				URI:      fieldURI,
				Name:     fieldName,
				DataType: fieldType,
			},
		}
		if elem, ok := elemByURI[elemURI]; ok {
			elem.FieldValues = append(elem.FieldValues, fv)
		}
	}
	return rows.Err()
}

// ElementUpdated is the resolver for the elementUpdated field.
func (r *subscriptionResolver) ElementUpdated(ctx context.Context) (<-chan *model.Element, error) {
	panic(fmt.Errorf("not implemented: ElementUpdated - elementUpdated"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))
	todo := &model.Todo{
		Text:   input.Text,
		ID:     fmt.Sprintf("T%d", randNumber),
		UserID: input.UserID,
	}
	r.todos = append(r.todos, todo)
	return todo, nil
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	return r.todos, nil
}
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	return &model.User{ID: obj.UserID, Name: "user " + obj.UserID}, nil
}
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }
type todoResolver struct{ *Resolver }
*/
