type Element {
  uri: String!
  title: String!
  type_uri: String!
  space_uri: String!
  creation_date: String!
  author: String!
  field_values: [FieldValue!]!
}

type FieldValue {
  uri: String!
  value: Any
  field: Field!
}

type Field {
  uri: String!
  name: String!
  data_type: String!
  options: Any
  required: Boolean!
}

type ElementConnection {
  edges: [ElementEdge!]!
  pageInfo: PageInfo!
}

type ElementEdge {
  cursor: String!
  node: Element!
}

type PageInfo {
  hasNextPage: Boolean!
  endCursor: String
}

input FieldValueFilter {
  field_uri: String!
  value: String!
}

type Query {
  elements(
    first: Int
    after: String
    filter: FieldValueFilter
  ): ElementConnection!
}

type Mutation {
  updateElement(
    uri: String!
    title: String!
    ): Element!
}

type Subscription {
  elementUpdated: Element!
}

scalar Any
