// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Element struct {
	URI          string        `json:"uri"`
	Title        string        `json:"title"`
	TypeURI      string        `json:"type_uri"`
	SpaceURI     string        `json:"space_uri"`
	CreationDate string        `json:"creation_date"`
	Author       string        `json:"author"`
	FieldValues  []*FieldValue `json:"field_values"`
}

type ElementConnection struct {
	Edges    []*ElementEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ElementEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Element `json:"node"`
}

type Field struct {
	URI      string `json:"uri"`
	Name     string `json:"name"`
	DataType string `json:"data_type"`
	Options  any    `json:"options,omitempty"`
	Required bool   `json:"required"`
}

type FieldValue struct {
	URI   string `json:"uri"`
	Value any    `json:"value,omitempty"`
	Field *Field `json:"field"`
}

type FieldValueFilter struct {
	FieldURI string `json:"field_uri"`
	Value    string `json:"value"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
